### PR TITLE
Fixes 136 - Fixed OpenSeaDragon viewer for objects with no representative id and improved test coverage.

### LINKED ISSUE #136: IIIF R&D
### Descriptive summary

Initial evaluation of IIIF options, particularly based on the excellent experience written up by Jonathan at CHF: https://bibwild.wordpress.com/2017/08/29/full-res-pan-and-zoom-js-viewer-on-a-sufiahyrax-app/

Of particular interest are:

- Evaluating [Cantaloupe](https://github.com/medusa-project/cantaloupe)
- Evaluating `vips` vs `graphicsmagick` vs `imagemagick` to generate static tilesets (as we've done w/ DAMS4). The performance gains from `vips` as written about, as well as `graphicsmagick` over `imagemagick` seem well worth exploring.

### Rationale

Based on the information we have available, we want to try and make the best decision about what to do with image derivatives.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #136

Fixed the error for OpenSeaDragon viewer for objects with no representative id and added more tests to improv test coverages.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
LGTM, @VivianChu thoughts?

**Comment by VivianChu** [comment]
@mcritchlow : Looks good 👍

File: spec/features/object_resource_spec.rb [hunk 1]
```diff
@@ -244,6 +244,34 @@
     end
   end
 
+  context 'IIIF OpenSeaDragon viewer' do
+    let(:user) { create(:admin) }
+    let(:object_with_file) { FactoryGirl.create(:object_with_image_file, title: ["Object - IIIF Viewer"], user: user) }
+
+    before do
```
Comment (mcritchlow) [inline spec/features/object_resource_spec.rb:251]: why is this needed? or rather, what would be the downside of just setting `iiif_enabled` to `true` in the [test environment](https://github.com/ucsdlib/horton/blob/a8f133a7f31417ece7f71c73c9d5b6433de04870/config/environments/test.rb#L62)? it seems you could do away with this before/after block setup/teardown entirely then.

Related, if we set it to true, then it seems we'd have that value set to `true` for all environments, which makes me wonder what the need for the configuration setting is, and the related checks for whether it's true or not, such as [this](https://github.com/ucsdlib/horton/blob/a8f133a7f31417ece7f71c73c9d5b6433de04870/app/views/hyrax/base/show.html.erb#L11)

**Review by mcritchlow — COMMENTED** [review]
@lsitu - thanks for adding these additional tests. 

I just one question about the config value for whether IIIF is enabled or not, and what value that brings us. Otherwise this looks great.

File: spec/features/object_resource_spec.rb (hunk 1 above)
Comment (lsitu) [reply spec/features/object_resource_spec.rb:251]: @mcritchlow I think the original thought is enable us to hide the viewer for any purpose. But since now we've added the mouse over trigger to have it shown up, so I think we can remove it.
I've updated the PR to remove the configuration: https://github.com/ucsdlib/horton/pull/138/commits/a975b474b0711dd81d4c852a74939e7a871c585f.

Comment (mcritchlow) [reply spec/features/object_resource_spec.rb:251]: Ah, ok. Yeah that sounds good. Thanks! @VivianChu do you have any other questions or concerns, or should we get this merged?

Comment (VivianChu) [reply spec/features/object_resource_spec.rb:251]: @mcritchlow - I don't have any other question.  We should get this merged.

**Review by VivianChu — APPROVED** [review]
